services:
  application-eval:
    container_name: application-eval
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - logs:/app/logs
    networks:
      - backend
      - proxy
    depends_on:
      - db

  front-end:
    container_name: front-end
    build:
      dockerfile: Dockerfile-Front
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - application-eval

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:1.27
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/templates/default.conf.template
    networks:
      - proxy
    depends_on:
      - application-eval
      - static

  db:
    container_name: db
    image: redis:7
    restart: unless-stopped
    volumes:
      - data_redis:/data
    networks:
      - backend

  static:
    container_name: static
    image: nginx:1.27
    volumes:
      - ./assets:/usr/share/nginx/html
    networks:
      - proxy

volumes:
  data_redis:
  logs:

networks:
  backend:
  proxy:

